#!/bin/bash -e

set -eu

export TF_IN_AUTOMATION=true

exec terraform init -input=false
exec terraform plan -input=false -out=terraform.plan
exec terraform apply terraform.plan -input=false -auto-approve
