#!/bin/bash -e

set -eu

export TF_IN_AUTOMATION=true

echo "initing"

terraform init -input=false

echo "planning"

terraform plan -input=false -out=terraform.plan

echo "applying"

terraform apply -input=false -auto-approve terraform.plan
